version: '3'
services:
  app:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    restart: always
    command: nginx -g "daemon off;"
    networks:
      - paperlive

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - '5000:5000'
    restart: always
    command: node index.js
    volumes:
      - ./server:/app
      - /var/backups/lig-paperlive-uploads:/app/uploads:rw
      - /app/node_modules
    networks:
      - paperlive

  database:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - /var/backups/lig-paperlive-db:/data:rw
    networks:
      - paperlive

networks:
  paperlive:
