version: '3'
services:
  app:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    ports:
      - '5173:5173'
    restart: always
    command: npm run dev
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URI=http://localhost:5000
    networks:
      - paperlive

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - '5000:5000'
    restart: always
    command: npm run dev
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - paperlive

  database:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - ./server/data:/data/db
    networks:
      - paperlive

networks:
  paperlive:
