version: '3'
services:
  app:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    command: nginx -g "daemon off;"
    networks:
      - paperlive

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - '3000:3000'
    command: node index.js
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - paperlive

  database:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./server/data:/data/db
    networks:
      - paperlive

networks:
  paperlive:
