version: '3'
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '3000:3000'
    command: npm run dev
    volumes:
      - ./server:/app
      - /app/node_modules
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./server/data:/data/db
